### ISSUE TITLE
Drawing Energy levels

### ISSUE THREAD

**Issue by aburousan** [SotaYoshida/ShellModel.jl#5]
It's not a issue, rather it's a question. Is it possible to plot energy levels like the figure given below for different potentials like harmonic, square well, wood ?
![images](https://user-images.githubusercontent.com/60939745/125581667-260a72fb-34df-483f-aae3-bd272af200df.png)
Can you add few examples on this if it's possible?

**Comment by SotaYoshida** [comment]
Hi, thank you for opening an issue on ShellModel.jl
 > Is it possible to plot energy levels like the figure given below for different potentials like harmonic, square well, Woods-Saxon?

The answer is yes. I would like to clarify your question a bit more.
Do you need functions to calculate one-body potentials under arbitrary parameters (e.g. LS-splitting or Woods-Saxon diffuseness parameter), and to plot them?

If so, I will consider to implement it.
Actually, visualization codes (for energy spectrum, EM transitions, etc.) is one of the many TODOs 😄

**Comment by aburousan** [comment]
Yes... Actually I was writing an article for my college project and there I have to analyse the LS splitting or energy levels for different potentials and to show the formation of magic numbers. But can't find any proper tool to do so. So I was wondering if we can do that using shell.jl😅... It will be really helpful

**Comment by SotaYoshida** [comment]
I see.
Finding one-body potentials is much simpler than what is done in ShellModel.jl, i.e., solving many-body eigenvalue problems etc.
You can find a much simpler codes to solve e.g. WS potentials [https://github.com/search?q=Woods-saxon](https://github.com/search?q=Woods-saxon), and detailed information on these from Lecture note by B.Alex Brown at MSU
👍
