### ISSUE TITLE
Arpack installation error in Julia with Intel MKL

### ISSUE THREAD

**Issue by MGYamada** [SotaYoshida/ShellModel.jl#6]
Is it possible to change Arpack.jl to e.g. KrylovKit.jl?
The installation of Arpack.jl fails in Julia with Intel MKL.

**Comment by SotaYoshida** [comment]
Thank you for your feedback.
The reason I chose Arpack.jl is just my preference of the interface.
I will replace Arpack.jl with KrylovKit.jl after I see if the results are reproduced.

Just for your info, Arpack.jl is called only in `src/eigenvector_continuation.jl`,
so you can just comment out `using Arpack` in `src/ShellModel.jl` for "ordinary" shell-model calculations.

**Comment by MGYamada** [comment]
Thanks! I will wait for PR.

**Comment by MGYamada** [comment]
package_install.jl is not yet fixed.
